### ISSUE TITLE
Contacts list dividers

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#100]
- They shouldn't be colored Nextcloud blue, it's too much and breaks the list. Instead just white
- The letter should left-align with the people's names, so move a bit to the right
- Can the divider be a bit transparent/blur elements behind, like on iOS or our server in the file list?

**Comment by mario** [comment]
- The divider is never blue. The header of a contacts group is, however.
- The current design is standard. There's a reason why header text starts earlier. Just like when you do lists and sublists, you use indentation.
- What divider? The header or one that divides the items? In either case, not convinced since this is not standard across Android.
