### ISSUE TITLE
Show own avatar when camera is disabled

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/talk-android#102]
Currently there is no feedback how you will look to other participants. In the server we show your own avatar because of that. We should do the same when you deactivate your video.

As discussed, for this reason we should also show your avatar in place of the settings icon in the bottom bar.

**Comment by mario** [comment]
The idea that we should pollute space (on a limited screen) with a largely meaningless avatar is probably not a good one. But I think @Ivansss has this, so for consistency sake, and because I don't care too deply, I'll do it.

**Comment by Ivansss** [comment]
I removed the avatar for space reasons. 
Also because with the new calling UI (buttons at the bottom) it didn't like the avatar hanging up there (see image below).
I added the avatar in the past because there were buttons (audio and video) next to the local video.

![img_0127](https://user-images.githubusercontent.com/4638605/36729605-11ec99c0-1bc5-11e8-91f2-926c6ef419d4.PNG)

**Comment by mario** [comment]
Good so I can close this too :P
