### ISSUE TITLE
automatically scroll to quoted message

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#1090]
add the ability to tap on a quoted message to automatically scroll to it

**Comment by Valdnet** [comment]
A very useful function. This is missing from Talk Android.

**Comment by rapterjet2004** [comment]
Hey, this sounds like a cool issue! 

I'm guessing that this would involve some kind of onClickListener on the message quote in [IncomingTextMessageViewHolder.kt](https://github.com/nextcloud/talk-android/blob/master/app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt), but since I'm controlling the scroll I'll probably have to pass in a ChatController object from [TalkMessagesListAdapter.java](https://github.com/nextcloud/talk-android/blob/8ae9985009cbe9c0b87209037d1bd86e2153c82c/app/src/main/java/com/nextcloud/talk/adapters/messages/TalkMessagesListAdapter.java) in the `onBindViewHolder()` method right? Probably using a helper method in `IncomingTextMessageViewHolder` to set the onClickListener onto the actual quoted message view.

I know that the quoted message text is taken from a `ChatMessage` Object called `parentMessage`. I'm not exactly sure how I'll be able to access the scroll position of view associated with `parentMessage` though. The only thing I can think of is to somehow find the object associated with `parentMessage` in the list of Chat Messages called `items`, and using it's index as a scroll position?
