### ISSUE TITLE
Push to talk instructions unclear

### ISSUE THREAD

**Issue by maulwuff** [nextcloud/talk-android#116]
The instructions for push to talk don't make clear what to do. The location goes to a position on my phone where there is no button.

The text only says to push and hold the button, but doesn't make clear which one. Vol up, vol down, power?

**Comment by mario** [comment]
Uh. What phone and what Android version? Basically the animation is just flawed then :-/

With microphone disabled, click & hold to use push-to-talk.

**Comment by mario** [comment]
(The microphone button obviously)

**Comment by maulwuff** [comment]
Lol ok.
I assumed that the blue line animation should tell me to push vol up/down or power button to use for ptt. It lines up perfectly between the vol rocker and the power button. (bq aquaris x5 plus) 




Am 17. März 2018 11:37:31 MEZ schrieb "Mario Đanić" <notifications@github.com>:

**Comment by mario** [comment]
So the animation works and it stars from the microphone button at the
bottom?

**Comment by maulwuff** [comment]
Yes it starts from the bottom to where  the vol keys are located.
![screenshot_20180317-115042](https://user-images.githubusercontent.com/4960210/37554503-3e0718f0-29da-11e8-9f88-8e2676294b8a.png)

Maybe just leave out the 90° bend to not confuse useres that they can't use the hardware buttons?

**Comment by maulwuff** [comment]
I assumed that it is intended to be used when the screen is off.
Sorry for the confusion ;-)

Am 17. März 2018 14:03:11 MEZ schrieb "Mario Đanić" <notifications@github.com>:

**Comment by mario** [comment]
I could try to implement that too, sure. But I need to think how. Hijacking volume buttons might not be a smart idea :)

**Comment by mario** [comment]
Sorry, nobody complained about this still :(

If people complain, I'll re-open the issue though!

**Comment by SteveYoungs** [comment]
Complaining, LOL.

No, seriously, the graphic is extremely misleading.  I, too, thought you were supposed to press one of the hardware keys. I've only seen the animation once (never tried again because pressing my hardware keys did not, obviously, work so assumed the feature was as yet not fully implemented), but doesn't the animation travel _from_ the mic button and finish at the upper right side of the screen (right next to the hardware keys)?  Yeah, that's completely backwards.  It draws your eye _away_ from the mic button (works too, I didn't even see the mic button, lol).

How I'd fix this:  Get rid of the blue horizontal and vertical lines and simply pulse the mic button.  Oh, and keep it pulsing until the user taps it for the first time.  Perhaps also keep the written instructions on screen for a few seconds longer (they'd vanished before I had had a chance to read them when I saw this).
