### ISSUE TITLE
Posting a "local" link hides the information

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#1167]
### Steps
1. In a conversation post a link from a local server, e.g. http://nextcloud21.local/apps/files/img/add-color.png which is my dev instance but not available with that fake domain outside of the maschine.
2. In the web UI I simply see a link to `http://nextcloud21.local/apps/files/img/add-color.png`
3. The android app only shows a blank space because it can't generate a preview for the link:
![Screenshot_2021-04-27-09-33-44-941_com nextcloud talk2](https://user-images.githubusercontent.com/213943/116203311-d85fd400-a73b-11eb-8758-7bb08cca3153.jpg)

In this case it should fall back to a text message showing the link

**Comment by AndyScherzinger** [comment]
Links aren't preview-rendered anymore, so this is drive-by-"fixed"

**Comment by timkrueger** [comment]
It looks like there is too much magic. The Method `TextMatchers#getMessageTypeFromString` tries to guess MIME types and returns a `ChatMessage.MessageType` :

https://github.com/nextcloud/talk-android/blob/b5cc62277d2a11820dcce7976b32508fadaa3bab/app/src/main/java/com/nextcloud/talk/utils/TextMatchers.java#L45-L88

Since in spreed and the iOS Talk app only links will be shown we don't need that mime suggestion anymore and it can be removed!?

**Comment by AndyScherzinger** [comment]
> Since in spreed and the iOS Talk app only links will be shown we don't need that mime suggestion anymore and it can be removed!?

I'll leave this up to @nickvergessen for aligment reasons (could also be that web/ios would "need" to implement it.)

@timkrueger What is the result/behavior due to these different message types? prefetching/rendering for certain types of files that URLs might point to? If so I'd also say, just always render as text.

**Comment by timkrueger** [comment]
> @timkrueger What is the result/behavior due to these different message types? prefetching/rendering for certain types of files that URLs might point to?

Yes.

>  If so I'd also say, just always render as text.

That was my plan. Thank you for the confirmation.  :+1:

**Comment by AndyScherzinger** [comment]
@timkrueger I also said this 😁 

> I'll leave this up to @nickvergessen for aligment reasons (could also be that web/ios would "need" to implement it.)

**Comment by nickvergessen** [comment]
Just for the record:
Totally fine with the removal. There is a "link preview" setting in the settings dialog which I guess can also be removed now?

**Comment by timkrueger** [comment]
>  There is a "link preview" setting in the settings dialog which I guess can also be removed now?

I'll take a look.
