### ISSUE TITLE
Unable to connect from Talk client v11.1.0 to Talk server 12.3 

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/talk-android#1663]
## Steps to reproduce
1. Download Talk for Android version [v11.1.0](https://github.com/nextcloud/talk-android/releases/download/v11.1.0/v11.1.0.apk) 
2. Try to connect to a Nextcloud 22 server with Talk enabled
3. At the final step, get "No Talk app installed on the server"

### Expected behaviour
The connection should be successfully established

### Actual behaviour
Connection fails, get "No Talk app installed on the server"

## Device information

**Device:** Huawei P8 lite 2017

**Android version:** 8.0.0

**Talk version:** 11.1.0

## Server information

**Nextcloud version:** 22.2

**Talk version:** 12.3

**Custom Signaling server configured:** don't know

**Custom TURN server configured:** don't know
**Custom STUN server configured:** don't know

**Comment by nickvergessen** [comment]
Not sure what's the best way to handle this. I guess we also need a "max" version check? With 12 only APIv4 is available I think, but maybe we just implemented the check with Talk Android 12, so with Talk Android 12 and a higher server version it wouldn't break anymore but report properly?

**Comment by nickvergessen** [comment]
cc @Ivansss as I assume the same issue exists on iOS

**Comment by pmarini-nc** [comment]
It would be great to have a compatibility matrix in the documentation. Something to inspire on would be [this post](https://nextcloud.com/blog/nextcloud-files-for-desktop-android-and-ios-introducing-support-for-nextcloud-hub-ii-features-and-more-major-improvements/), section "Technical details and compatibility", but in the admin documentation.

**Comment by Ivansss** [comment]
| Talk iOS | Requirements|
|---|---|
|  iOS version | 10.0 + |
| Nextcloud version | 14.0 + |
| Nextcloud Talk version | 4.0 + |
| Supported devices | iPhone, iPad, iPod touch and Mac with M1 chip |

**Comment by mahibi** [comment]
Requirements for Android Talk App 12.1+ until the current version (13.0) are:

| Talk Android | Requirements|
|---|---|
| Android OS | 5.0 + |
| Nextcloud version | 14.0 + |
| Nextcloud Talk version | 4.0 + |

see 
- https://github.com/nextcloud/talk-android/blob/master/app/build.gradle#L41
- https://github.com/nextcloud/talk-android/blob/9173bfbdafd9f9119252677296fbb3ff85fffd17/app/src/main/java/com/nextcloud/talk/models/database/CapabilitiesUtil.java#L69

The Android Talk App below v12 can handle a server with Nextcloud Talk 12.0+ (because of APIv4).
So whenever the "No Talk app installed on the server" error occurs the Android App should be updated to the newest version, or at least to v12.1

**Comment by pmarini-nc** [comment]
Thanks @mahibi and @Ivansss ! 

I would recommend putting this valuable information in the documentation in the following form:

| Talk Android (iOS) | Android OS (iOS) | Nextcloud Server | Talk |
|-----|-----|-----|-----|
| 11.0 | >=5.0 |  >= X1.Y1, <= X2.Y2 | >= X1.Y1 | 
 
In this way the Nextcloud admin can easily check this information when planning for a server or app upgrade. This is just an example and there may be redundant or missing information in the above table.

**Comment by mahibi** [comment]
https://github.com/nextcloud/documentation/pull/7823
