### ISSUE TITLE
Disable proximity sensor for video calls

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/talk-android#1721]
Currently WhatsApp, google due have this feature while on a video call the camera or screen dose not turn off is very frustrating when going over the proximity sensor and camera turns off and screen turns off and sometimes it dose not come back on. Very similar to  #758, #920, #638. 

Please anyway we can get an option to disable the proximity sensor!! 🙏

**Comment by andyxheli** [comment]
I found a reference from signal thats how they went about it. Any thoughts ?
https://github.com/elliptic1/Signal-Android/commit/1666f4b6043572a19402f5b5d91e9b16a5894236

**Comment by dsbert** [comment]
Hmm this issue was closed as completed, but as far as I can tell, the linked PR has nothing to do with it?

I'm still running into this problem on a tablet running lineage OS. The proximity sensor seems to trigger constantly and the screen is always turning off during a call. It's very difficult to get it to turn back on. I realize this may be something in the device/OS level, but having the ability to disable the proximity sensor would be amazing since the OS doesn't seem to have any option to address this.
