### ISSUE TITLE
Searching for contacts returns only a subset of users

### ISSUE THREAD

**Issue by brtptrs** [nextcloud/talk-android#174]
When searching for contacts in the Android app only the pre-loaded contacts seem to be taken into account. In our case this means the fast majority of contacts can not be contacted via the Talk app.
App Version: v1.2.0beta2
Talk: 3.2.1
NC: 13.0.2

**Comment by brtptrs** [comment]
We are happy Nextcloud customers already :-)
I have also opened a support ticket

**Comment by mario** [comment]
Yay for that! :D

**Comment by brtptrs** [comment]
It seems like around 50 contacts get pre-loaded and ca be searched, the rest are ignored.

**Comment by mario** [comment]
Should really be 200 because that's what I ask Nc instance for and then do local search, but it's possible there's a bug in there somewhere. However, a solution to the problem is three-fold really:

- [ ] - Allow loading more contacts once you reach the bottom
- [ ] - Use remote search instead of local one
- [ ] - Perform local search only if target set is less than 200 users

**Comment by mario** [comment]
@brtptrs found why it might be 50.

**Comment by mario** [comment]
@brtptrs since you already have a support ticket, let's handle it there! :)

**Comment by brtptrs** [comment]
@mario Beta3 now works as expected. Thanks for the professional assistance!!

**Comment by mario** [comment]
@brtptrs happy to be of help! :)
