### ISSUE TITLE
Allow to select audio output channel

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#1761]
It should be possible to select the audio output (speaker, earphones, bluetooth, ....)

Ref https://github.com/nextcloud/talk-ios/issues/712

**Comment by mahibi** [comment]
lets stick to these terms to avoid confusion:

- earspeaker (=built in)
- speaker (=built in)
- headset via cable (with mic)
- bluetooth speaker (no mic)
- bluetooth headset (with mic)

so i made the follwing tests:

# calls
- switch between earspeaker and speaker via button:
   - possible via button in call screen
- switch between earspeaker and speaker via proximity sensor:
   - works

- when using an external headset via cable:
   - works. this is used instead of the speaker or earspeaker. 
	- atm the button to switch between speaker or earspeaker has no function in this state. This might be improved be disabling it.

- when connected to bluetooth speaker:
   - this won't be used. (and it shouldn't)
- when connected to bluetooth headset:
   - will be used.

- switch from earspeaker/speaker to bluetooth headset by activating/deactivating bluetooth in android quicksettings: 
   - not reliable (had one time the bug that speaker from headset was used but mic from smartphone)

- switch from earspeaker/speaker to bluetooth speaker by switch button:
   - no button available yet. might require research if it's possible at all.
	

# media playback (incl. voice messages)
- switch between earspeaker and speaker via button:
   - not yet possible (which is also not necessary in my opinion)
- switch between earspeaker and speaker via proximity sensor:
   - not yet possible. this must be improved: https://github.com/nextcloud/talk-android/issues/1354

- when using an external headset via cable:
   - this is used instead of the speaker or earspeaker

- when connected to bluetooth speaker:
   - this will be used to playback media and voice messages			

- switch from earspeaker/speaker to bluetooth speaker by activating/deactivating bluetooth in android quicksettings: 
   - works
- switch from earspeaker/speaker to bluetooth speaker by switch button:  
   - no button available yet. but it's possible to select it in android >= 11 if we implement this in combination with a notification, which makes sense anyway. https://developer.android.com/guide/topics/media/media-controls


@nickvergessen please clarify what should be done with this issue

**Comment by nickvergessen** [comment]
> * when connected to bluetooth headset:
>   * will be used.
>
> …
> * switch from earspeaker/speaker to bluetooth speaker by switch button:
>   * no button available yet. might require research if it's possible at all.



So I guess this is one of the things. When I'm in the car and connected with bluetooth, I need to be able to switch to earspeaker without having to kill bluetooth (which would also disconnect the watch, etc.)

**Comment by mahibi** [comment]
ok, so what about making a fold out menu with current available options. just a quick&dirty mockup:

![grafik](https://user-images.githubusercontent.com/2932790/151537954-62740b85-1513-4989-a816-eac4ff95d65d.png)

what do you think @nickvergessen @jancborchardt @Ivansss ?

**Comment by nickvergessen** [comment]
@AndyScherzinger ^ also your understanding?

**Comment by AndyScherzinger** [comment]
I'd have some suggestions, please see the screenshots from signal as well as phone (both Android 12)

|Phone|Signal|
|---|---|
|![Screenshot_2022-01-28-17-22-43-70_54063fc6848ac98a54ce5f2a63661433](https://user-images.githubusercontent.com/1315170/151584867-3b428ee5-b447-4e81-a85b-0cc5a20564fc.jpg)|![Screenshot_2022-01-28-17-24-08-86_4b14b257287ac0a6d1fd5fbb2487716f](https://user-images.githubusercontent.com/1315170/151584897-8d7e8a79-be33-4f5c-b2f6-f4d179a29ef1.jpg)|

Looking at the screenshots from above, I would suggest to go with the phone-like experience:
* go with a bottom sheet (phone screenshot) including the text and icons, that way it is easy to understand what you are about to pick
* highlight the active one in the bottom sheet
* have also the "arrow down" icon on the fab to indicate that there are options to choose (for now that might mean duplicating the icons - this can be postponed or you ping me with enough time in advance than I can help with the icons)

Icons (choose android and then use the drawable-xml from the zip archive):
- bluetooth https://fonts.google.com/icons?selected=Material%20Icons%3Abluetooth_searching%3A 
- speaker https://fonts.google.com/icons?selected=Material%20Icons%3Abluetooth_searching%3A
- phone-speaker https://fonts.google.com/icons?selected=Material%20Icons%3Aphone_in_talk%3A
