### ISSUE TITLE
🤖 Android update WebRTC library

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#1773]

**Comment by mvarchdev** [comment]
Hello. I have a problem that when WebRTC Signalling server is used, everything is working fine, calls through browser on android phone and on pc are working. But on app Nextcloud Talk not... Is this issue releated to this?

**Comment by timkrueger** [comment]
@mvarchdev: Sorry for the delay.

> app Nextcloud Talk not... Is this issue releated to this?

I think not. This issue is related only to update the underlying WebRTC library in Talk for Android. 

For help please ask in the [community](https://help.nextcloud.com/c/support/talk/52). 

If you're sure you found a new bug, please create an issue in the [spreed (Talk)](https://github.com/nextcloud/spreed/issues) repository or in the [talk-android](https://github.com/nextcloud/talk-android/issues) repository.
