### ISSUE TITLE
[v14rc2] Multiple reactions break chat room

### ISSUE THREAD

**Issue by XueSheng-GIT** [nextcloud/talk-android#1937]
## Steps to reproduce
1. Enter chat room
2. Make two or more reactions to the same message
3. Leave room
4. Enter room again

### Expected behaviour
Room should be opened and messages/reactions be shown.

### Actual behaviour
Room could not be opened (loading screen). See video below.
https://user-images.githubusercontent.com/4077683/164523375-0f1a6c62-46a8-463e-b97e-a9661b8ae655.mp4

## Device information

**Device:** Huawei Mate 40 Pro (NOH-NX9)

**Android version:** 10

**Talk version:** 14.0.0 RC2

## Server information

**Nextcloud version:** 24.0.0 RC1

**Talk version:** 14.0.0-rc.2

**Custom Signaling server configured:** no

**Custom TURN server configured:** no

**Custom STUN server configured:** no

**Comment by mahibi** [comment]
this is most likely because of the self reactions which couldn't be parsed when using talk 14.0.0-rc.2 on server. Some device might even crash here because of low memory.

This is fixed with
https://github.com/nextcloud/spreed/pull/7182
on server side. 
Once this is released, the self reactions will then be correctly shown the next android talk app release which will contain
https://github.com/nextcloud/talk-android/pull/1934

If you already want to test, you would have to use the latest master of spreed and install the app from https://github.com/nextcloud/talk-android/pull/1934

**Comment by mahibi** [comment]
i added the "to review" label so we don't forget to test when the fixes are deployed...

**Comment by XueSheng-GIT** [comment]
Issue seems to be solved after updating to talk 14.0.0-rc.3 on the server!

**Comment by mahibi** [comment]
> Issue seems to be solved after updating to talk 14.0.0-rc.3 on the server!

this confirms my theory. I will close this issue, thanks for testing :+1:  
With the next Android Talk RC the self reactions will then be correctly shown.
