### ISSUE TITLE
Forward is not cleared after forwarding

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#1981]
## Steps to reproduce
1. Have a message/text in another app that allows forwarding
2. Forward to talk android
3. Go to a conversation and post it.
4. Go back to the overview
5. Click on another unread chat

### Expected behaviour
Cleared behaviour

### Actual behaviour
Input is filled with the same text again?

Not sure if this is expected, for me it's unexpected every time it happens.

**Comment by nickvergessen** [comment]
![threema-20220511-163752655.jpg](https://user-images.githubusercontent.com/213943/167876464-353fbcc3-9370-491e-937b-7dc7f6c1c66e.jpg)

As you can see i just forwarded it to you, i press back amd it shows the forwarding headline again

**Comment by mahibi** [comment]
aaah you mean the appbar header. so the error you describe is in step 4...

**Comment by nickvergessen** [comment]
Yeah and when from there you go to any other app it forwards the details again

**Comment by mahibi** [comment]
i guess in short term the line

`showShareToScreen = !showShareToScreen && hasActivityActionSendIntent();`

in https://github.com/nextcloud/talk-android/blob/master/app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java#L360

might cause the bug and could be changed.

But the best solution for this would be that we create a seperate view instead of reusing the ConversationsListController for sharing/forwarding actions. But this would take a bit longer...

**Comment by nickvergessen** [comment]
Okay, anything but a quickfix os out of scope. So let's just keep the ticket in the backlog if anyone ever wants to do it.

I thought maybe its as simple as clearing a variable on posting

**Comment by mahibi** [comment]
> i guess in short term the line
> 
> `showShareToScreen = !showShareToScreen && hasActivityActionSendIntent();`
> 
> in https://github.com/nextcloud/talk-android/blob/master/app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java#L360
> 
> might cause the bug and could be changed.

might be caused by commit https://github.com/nextcloud/talk-android/commit/cf471e336f9f0a9623b224e75f551c190f2cf5a9
