### ISSUE TITLE
🙋 Allow guests

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#2134]
For an existing conversation it is not possible to allow/disallow guests

**Comment by timkrueger** [comment]
Sorry that this needs so long to start with this issue.

I found that this is already implemented. In the conversation list long press a conversation. If you're a moderator you can make a group conversation public. In an second step also an password can be set.

https://user-images.githubusercontent.com/606665/185195242-7d1af8db-840b-40c5-a1d2-eeef9e5cf1fd.webm

But I would rather have it in conversation info like in iOS and spreed. Because I started with the UI I can show the current state:

<img width="300" href="https://user-images.githubusercontent.com/606665/185196687-0661e2bb-17c8-44c9-9fa0-ee2b22c2d171.png" />

@nickvergessen, @mahibi  : Do you agree to move the guests access configuration to the Conversation info and remove it from the button sheet?

**Comment by nickvergessen** [comment]
Yeah i was surprised to find it in the long press the other day while searching for "mark as unread".
So good idea to remove it there while adding it in the conversation settings
