### ISSUE TITLE
Ability to zoom out video while on the call 

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/talk-android#2200]
## Steps to reproduce
1. Join Call 
2. Everyone Looks zoomed in
3.

### Expected behaviour
 When joining a call the other user looked zoomed in on the phone. There should be an option to double tap on the screen and the vedio gets zoomed out. This is how it works on the iOS Talk App

### Actual behaviour
Android dose not have this option.

## Device information

**Device:** Fairphone2/…
S21+ 5G, SM-G996U1
**Android version:** 10/…
Android 12
**Talk version:** 11.0.0
NC 14.0.1 RC1
## Server information

**Nextcloud version:** (see admin overview page: `/index.php/settings/admin/overview`)
NC 24.0.3 RC3
**Talk version:** (see apps admin page: `/index.php/settings/apps`)
14.0.3

**Comment by lbdroid** [comment]
Any connection? https://github.com/nextcloud/talk-android/issues/2052

**Comment by andyxheli** [comment]
Hi @ASerbinski wpuld this be the same as the ticket you created that mentioned above ?

**Comment by ASerbinski** [comment]
@andyxheli I think it would fix the problem you are experiencing, since it would set everybody universally to zoom out to maximum. The problem you're experiencing seems to be that the video streams being sent by other participants are zoomed in (cropped) way too much, which is what my patch is designed to fix. You can't really change that on YOUR side, since it would have to control other peoples' cameras.

**Comment by andyxheli** [comment]
Perfect! Thank you so much for the explanation. 😁 should I close this ticket then?
