### ISSUE TITLE
Rename shared file if one with same file name already exists

### ISSUE THREAD

**Issue by dontinelli** [nextcloud/talk-android#2280]
## Steps to reproduce
1. Share e.g. picture with nextcloud talk app
2. File is uploaded
3. After upload, all pictures with (presumably) same file name in chat have "changed", as new picture is displayed

For me this is very annoying, as I for example regularly share a snip of the train timetable (which apparently always gets the same filename from the exporting app). With sharing a new timetable, all other ones are overwritten.

### Expected behavior
If file to be uploaded has a file name name that already exists, I see different options to handle (and of course there are more):
1. File is automatically renamed to prevent conflict
2. User is asked if he wants to overwrite, rename or share link to existing file
3. It is verified, if files are identical. If not, uploading file is renamed, if yes, user is asked if he wants to upload anyway or share link to existing file

### Actual behaviour
Existing file is overwritten.

## Device information

**Device:** Samsung Galaxy Note9 (but I guess this is HW-independent)

**Android version:** 10

**Talk version:** 14.1.0 (but I had same issue ever since)

## Server information

**Nextcloud version:** 24.3

**Talk version:** 14.0.3

**Custom Signaling server configured:** no/talk#signaling_server`)

**Custom TURN server configured:** no

**Custom STUN server configured:** no

### Server log (data/nextcloud.log)
n/a

**Comment by mahibi** [comment]
fixed with https://github.com/nextcloud/talk-android/pull/2351

**Comment by migulen** [comment]
@mahibi , @AndyScherzinger,

Actually, the solution chosen to this issue is:

1.- File is automatically renamed to prevent conflict  

This solution is quick... but it duplicate (triplicates, etc...) the files at server if you want to send it (quickly) to different conversations, and not entering to nextcloud client app (files) each time to share between X conversations  ). 

IMHO, the preferred way will be (by order):

3.- Checksum files, if files are identical, (add)share the link to his conversation directly (**). 
                    If not identical, ask the user if he wants:
                       - upload_overwrite the file at server and (add)share the link to the conversation,
                         or
                       - upload the file renamed and (add)share the link to the conversation. 

(**) I think, It could have side effects not allowing to "upload_renamed" if identical... could be "upload_renamed" is necessary for some situations...


2.- User is asked if he wants to overwrite, rename or share link to existing file <--- If the above protocol (3.) it's too much work for coding it :-).

@dontinelli what do you think ? I like your options.

**Comment by migulen** [comment]
Hi @mahibi  , @AndyScherzinger  , **may I reopen an issue to take a second mind/chance about this ?**

> @mahibi , @AndyScherzinger,
> 
> Actually, the solution chosen to this issue is:
> 
> 1.- File is automatically renamed to prevent conflict
> 
> This solution is quick... but it duplicate (triplicates, etc...) the files at server if you want to send it (quickly) to different conversations, and not entering to nextcloud client app (files) each time to share between X conversations ).
> 
> IMHO, the preferred way will be (by order):
> 
> 3.- Checksum files, if files are identical, (add)share the link to his conversation directly (**). If not identical, ask the user if he wants: - upload_overwrite the file at server and (add)share the link to the conversation, or - upload the file renamed and (add)share the link to the conversation.
> 
> (**) I think, It could have side effects not allowing to "upload_renamed" if identical... could be "upload_renamed" is necessary for some situations...
> 
> 2.- User is asked if he wants to overwrite, rename or share link to existing file <--- If the above protocol (3.) it's too much work for coding it :-).
> 
> @dontinelli what do you think ? I like your options.

**Comment by mahibi** [comment]
the current renaming solution was chosen because it is the same way the talk web app (spreed) behaves.
I think this solution is chosen in spreed to simplify the logic which file is shared to which users.
Unless spreed does not change this behaviour it won't be changed for the android app.
You could open an issue in spreed to discuss this further if you like.
