### ISSUE TITLE
Better in-chat media preview 

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/talk-android#2366]
I don't know how hard it would take to implement but it sure would be nice.

Here's an in-chat image preview on Nextcloud Android Talk  and the corresponding view on Telegram 

Talk ![Screenshot_20220913-144506_Talk QA](https://user-images.githubusercontent.com/59488153/189995578-654688f9-148d-4cbd-94e8-f2ea897efcf6.jpg) Telegram![166503232-759961f1-37eb-42ce-af07-e93fb289b864](https://user-images.githubusercontent.com/59488153/189995739-cf147475-08e9-4907-b44c-6d703cfd73e0.jpeg)

Similar too https://github.com/nextcloud/talk-ios/issues/776

**Comment by AndyScherzinger** [comment]
@andyxheli is the image in both screenshots the same one, since one seems to be a photo from a monitor image and with a different image ratio, no?

**Comment by andyxheli** [comment]
Hi @AndyScherzinger what I mean is maybe removing the name of the photo from that chat and making it similar to telegram 

Telegram
![Screenshot_20220913-150520_Telegram](https://user-images.githubusercontent.com/59488153/189999097-c8db1d57-733c-420c-a245-bdbf2dff1586.jpg)![Screenshot_20220913-150605_Talk](https://user-images.githubusercontent.com/59488153/189999105-0107b873-e5c4-4594-86ad-de1ab5507c98.jpg)


I'm sorry about that bad photos

**Comment by mahibi** [comment]
needs to be aligned with the talk iOS app. there we also have the filename under the photos. on web it's a mouseover tooltip.

if we decide to hide the filename then it would also make sense to move the time onto the photo like telegram does..
the filename would still be visible when opening the photo in fullscreen..

**Comment by AndyScherzinger** [comment]
I think this would be a good approach while currently we do not have a dedicated "image-bubble" but a preview one and this approach only works well for images but not for other files like pdfs, so we would need to add a distinction and a specific image bubble I think.

**Comment by andyxheli** [comment]
Hey guys here's a screenshot of how it looks when you send photos with big file name. Personally it would be nice to remove the name of the photos from the viewer ![Screenshot_20220918-162726_Talk.jpg](https://user-images.githubusercontent.com/59488153/190928794-3e027eba-99f9-4489-b445-5e592ff0bac6.jpg)

**Comment by AndyScherzinger** [comment]
@jancborchardt @nimishavijay what do you think? https://github.com/nextcloud/talk-android/issues/2366#issuecomment-1245901961

I like it and agree with @mahibi - if we do it we need to do it i Android _and_ iOS

**Comment by nimishavijay** [comment]
Agreed, file names for images are usually technical and not useful, so it makes sense to remove it.

As for an "Image bubble" I think it's a good idea. Telegram and WhatsApp have a bubble, and whenever there is an image caption it is a part of the bubble. So if we are planning to have image captions in the future a bubble is certainly the right direction.

Also agreed that the timestamp can be within the image. Note that there is always a half transparent black background with the timestamp text in white (in WhatsApp, Telegram and Signal) so that the timestamp is visible if the image is white.

For other file types, the name is useful but I think it can still be within a bubble and the name ellipsized, so that the size still remains consistent. Similar to WhatsApp and telegram

![Screenshot_20220919-174900_Telegram.jpg](https://user-images.githubusercontent.com/52440189/191059143-45663e16-3eb6-45a1-9ae8-bc39aa2afe64.jpg)

![Screenshot_20220919-174954_WhatsApp.jpg](https://user-images.githubusercontent.com/52440189/191059292-c4f2750d-abee-414e-a0a7-8d87adafee5c.jpg)

**Comment by jld3103** [comment]
Not implementing it until https://github.com/nextcloud/talk-android/issues/1552 is resolved

**Comment by louim-lbs** [comment]
I don't know about the overall plan, but #2366 (this issue) says the solution won't be implemented until #1552 is resolved. And #1552 says it won't be done until #2449 is merged.

With #2449 now merged, can we rethink #1552 and, eventually, #2366 (this issue), which I would very much like to see resolved?

Thanks!

**Comment by AndyXheli** [comment]
Hey I would agree any plans on getting this implemented?

**Comment by AndyScherzinger** [comment]
Well, all devs are currently busy with feature, of course contributions are aways welcomed, also for this one.
Maybe somebody finds the time when limiting it to image previews for the momentum and how the issue discussion initially started.
