### ISSUE TITLE
Ability to change time from 24 hour to 12 hour

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/talk-android#2369]
Is there a way to change the time in the app from 24 hours to 12 hours? Maybe have the app detect that way its setup on the phone so then it can also show under the Talk app. as of right now it runs on 24 hour time. Most of users in the US run on 12 hour time and some people cant read 24 hour time.

**Comment by jld3103** [comment]
It's not worth it to work on this right now, because the part that formats the times in the messages is inside ChatKit. See https://github.com/nextcloud/talk-android/issues/1552. This issue can still be open because it's a feature we'd want to have in the future, but only when a re-implementation of the chat UI is happening.
