### ISSUE TITLE
User status icon not showing under main screen

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/talk-android#2478]
Show user status icon under each users icon on main screen. 

Please see Android VS iOS

![image](https://user-images.githubusercontent.com/59488153/194893523-710d9a96-7082-473e-9107-2cc86cb38959.png)![image](https://user-images.githubusercontent.com/59488153/194893640-94184de2-cc43-4dd5-b521-db778c5c75aa.png)

**Comment by AndyScherzinger** [comment]
@andyxheli user status is displayed just fine for me on Android 🤔

**Comment by andyxheli** [comment]
@AndyScherzinger  Hmm dose it take a bit for the status to update ? i just tested and same results ios shows and android nothing im running v15.0.0 RC1 Android App

**Comment by andyxheli** [comment]
Working on testing on 14.2.0

**Comment by AndyScherzinger** [comment]
I don't know when the status gets fetched tbh, maybe @mahibi or @timkrueger know this.

**Comment by andyxheli** [comment]
I just tested on 14.2.0 and same results. I wish i could give more into :( sorry As of right the test user is logged in via web and i have both IOS and Android open at the same time and no status on the android. wired :(  but if click on the username name go to conversation info and scroll to the bottom i see a green icon but nothing under the main screen hope this helps

**Comment by mahibi** [comment]
the status in the conversation list ("main screen") should be updated e.g. when entering the conversation list and by pull down to refresh (spinner icon).

https://github.com/nextcloud/talk-android/blob/master/app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.kt#L504

can you confirm the status is still not seen when you refresh the list by pull down @andyxheli ?

**Comment by andyxheli** [comment]
Hi @mahibi yes I tried to refresh by pull down and no luck same issue

**Comment by mahibi** [comment]
can you do this curl request via console?

`curl -k -H "OCS-APIRequest: true" -u "yourusername:yourpassword" https://yoururl/ocs/v2.php/cloud/capabilities`

just replace yourusername, yourpassword and yoururl

the answer should contain 

```
   <user_status>
    <enabled>1</enabled>
    <supports_emoji>1</supports_emoji>
   </user_status>
```

where i'm especially interested if there is 1 as value for `supports_emoji`

**Comment by andyxheli** [comment]
Here's the output 
  <user_status>
    <enabled>1</enabled>
    <supports_emoji>1</supports_emoji>
   </user_status>
   <weather_status>
    <enabled>1</enabled>
   </weather_status>
  </capabilities>
 </data>

**Comment by andyxheli** [comment]
@migulen Can you confirm if you're having this issue also ?

**Comment by mahibi** [comment]
@andyxheli can you create a testaccount on your server and send url and credentials to 
marcel . hibbe at nextcloud . com
?

**Comment by andyxheli** [comment]
Just sent the info over :)

**Comment by mahibi** [comment]
interim status (thanks to @andyxheli ):

somehow the problem is related to "allow username autocompletion to users within same group".
if it's enabled: no status icons in the android talk app
if it's disabled: staus icons work in the android talk app
for iOS it always works

**Comment by mahibi** [comment]
The iOS app doesnt use the 
`/ocs/v2.php/apps/user_status/api/v1/statuses`
endpoint but uses

`"includeStatus=true"`
when fetching conversations, see https://nextcloud-talk.readthedocs.io/en/latest/conversation/

This solution makes more sense and this should also be used for the android talk app.

Anyway for now this perfectly explains the described issue and https://github.com/nextcloud/server/issues/34570 must be fixed.

For now i will keep this issue open and will have a look to use `"includeStatus=true"` to show the user statuses

**Comment by AndyScherzinger** [comment]
Nice catch and finding everyone! 🥇

**Comment by migulen** [comment]
> @migulen Can you confirm if you're having this issue also ?

Sorry @andyxheli , I didn't see the notification yesterday, and today I've been a little bit busy.

Yes, I confirm that I don't see  "User status icon under each users icon on main screen" (I can see it on "Conversation Information") with "nextcloud-talk android app" v15.0.0-RC4 and v15.0.0-RC5... and I think with all v15.0.0-RCx series. I can't see on a terminal with v14.2.0, so it's different situation than yours @andyxheli.  Could be I have disabled some option ?

**My Nextcloud server is v23.0.10 and  Spreed (talk) is v13.0.9.**

@mahibi, using an admin account  on my nextcloud server, I can't find on "Settings/Administration/Sharing" the option you mentioned:

"somehow the problem is related to "allow username autocompletion to users within same group". "  <--Could be it located on other place, or it's labeled different on v23,v24,v25 nextcloud server

I've only this settings in "sharing": 

![imagen](https://user-images.githubusercontent.com/60242624/195725112-975b3aff-73e0-4be1-a18f-3b7d8b4bf498.png)

and checked like that.  

**I wish it helps too.**

Thanks for all.
