### ISSUE TITLE
Duplicate group name when mentioning all in a group with emoji in title

### ISSUE THREAD

**Issue by arcstur** [nextcloud/talk-android#2496]
### Steps to reproduce

1. Create a group with an emoji in the group's title
2. Send a message "@ all" (without the space) in the group.

### Expected behaviour

The message should be a rounded corner rectangle with the group photo (default) and the group name inside it, only.

### Actual behaviour

The message appears duplicated, the expected rectangle appears twice, with an extra emoji in the middle.

### Device brand and model

Samsung A50

### Android version

11

### Nextcloud Talk app version

14.2.0

### Nextcloud server version

24.0.5

### Talk version

14.0.5

### Additional information

Here is a screenshot displaying the message, with the duplication error:

![photo_2022-10-14_00-46-38](https://user-images.githubusercontent.com/24514392/195757889-951c6e6b-6673-4d76-b025-d6bfdb6a24f3.jpg)

You can see that in the chat list view, the error **doesn't** occur:
![photo_2022-10-14_00-46-40](https://user-images.githubusercontent.com/24514392/195757942-a7d79b9f-df5f-4f28-a57a-710cdf11a603.jpg)

EDIT: added a space between @ and all to prevent GitHub mentions.

**Comment by mahibi** [comment]
Can reproduce this and it seems the bug exists since ever.
I had a look but unfortunately i have no idea what's going wrong here. 
It must be related to the spannable or chip i guess, so that's why it doesn't happen in the conversation list view (there it's just a TextView).

Maybe @AndyScherzinger has an idea?

**Comment by AndyScherzinger** [comment]
@mahibi The bug exists ever since and the reason is the spannable logic because -> it is not correctly calculating the start/end point for the replacement/placement of the chip as a span in the textview due to the fact that an emoji has more bits I think and hence the logic breaks and only works for "simple text" but I never found a way or the time to dig deeper into how the length can be calculated correctly.

**Comment by mahibi** [comment]
ah okay so i was was at the right track when looking at https://stackoverflow.com/questions/73595754/android-issue-with-rendering-emoji

thanks, for now i postpone but good to know where to have a closer look at next!
