### ISSUE TITLE
App crashes at the beginning of a call

### ISSUE THREAD

**Issue by csoc49** [nextcloud/talk-android#2789]
### Steps to reproduce

App crashes at the beginning of a call.
App Version: 15.1.2

### Expected behaviour

App crashed

### Actual behaviour

App crashed

### Device brand and model

Gigaset GS5

### Android version

12

### Nextcloud Talk app version

15.1.2

### Nextcloud server version

25.0.3

### Talk version

15.0.3

### Custom Signaling server configured

None

### Custom TURN server configured

Yes

### Custom STUN server configured

Yes

**Comment by mahibi** [comment]
Thank you for creating the issue @csoc49 :+1: 

For the sake of completeness I copy your description from gplay:
"App keeps crashing when trying to start or answer a call. OS: Android 12 Addition: Yes, the version is 15.1.2 The error has been occurring for about 2 months, unfortunately I don't know the working version. Yes, occurs on other devices too. Current device Gigaset GS5"

So ~2 months ago it could be version 15.0.3 that introduced the issue for you.
https://github.com/nextcloud/talk-android/releases

Could you install 15.0.2 and see if it works?
https://github.com/nextcloud/talk-android/releases/download/v15.0.2/15.0.2.apk 

Because you say it also happens with other devices, there might be some nextcloud config that is not handled correctly.
For best support, it would be great if you could create 2 testaccounts for me on your nextcloud instance so i can try to reproduce this. If you are okay with this, please send the credentials to    marcel dot hibbe at nextcloud dot com.

**Comment by mahibi** [comment]
might be fixed with https://github.com/nextcloud/talk-android/pull/2841
