### ISSUE TITLE
ability to use camera

### ISSUE THREAD

**Issue by jookk** [nextcloud/talk-android#306]
Straight from the app and paste image.

**Comment by feutl** [comment]
Having picture support, not in the nextcloud directory, would also be great.
Straight from the camera or the storage of the phone/tablet. This would allow the youngest family members to stick longer with Nextcloud Talk ;)

Also the same should apply for "invited" Users / Guest Users to allow them stick with a more secure solution as long as possible, instead of flipping to Whatsapp and others as soon as they have a phone number ;)

**Comment by lbdroid** [comment]
Even the nextcloud (files) application has an option to upload straight from the camera. This really is basic functionality and *every* other messaging application implements it. I'm surprised that it has been on the backburner for so long.

**Comment by jakobroehrl** [comment]
It would be great if there is a image/video compression before uploading like in the deck android app

**Comment by lbdroid** [comment]
Has this feature been added to the roadmap yet? Its about the most annoying missing feature.

**Comment by AndyScherzinger** [comment]
> Has this feature been added to the roadmap yet?

We don't do roadmaps, sorry

> Its about the most annoying missing feature.

This is your personal opinion :/ And as always: It is OSS, so PRs are welcomed!

On the up-side, I started working on it and might pushed a work-in-progress thing for the other devs to pick-up, see #1513 - So looping in @mahibi and @timkrueger - if you have the time to pick this up, feel free since I might not be able to further work on it in the very near future I am afraid :(

**Comment by AndyScherzinger** [comment]
> It would be great if there is a image/video compression before uploading like in the deck android app

@jakobroehrl can you raise this in a new issue? ❤️

**Comment by AndyScherzinger** [comment]
re-opened since the PR bringing direct cam upload hasn't been merged (and isn't complete yet), will auto-close when the PR is merged.

**Comment by AndyScherzinger** [comment]
PR is ready for review and got some polishing, so this should soon be ready for shipment :)
