### ISSUE TITLE
Chat is not updated

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#3146]
### Steps to reproduce

sometimes the chat screen doesn't refresh messages.

### Expected behaviour

chat updated

### Actual behaviour

chat not updated

**Comment by mahibi** [comment]
The issue happened another time after https://github.com/nextcloud/talk-android/pull/3147 was merged. 
So reopening as there must be more scenarios that trigger this bug.

**Comment by mahibi** [comment]
i guess somehow long-polling is interrupted because lookIntoFuture is false. 
Want to simplify the pullChatMessages logic in the long term..

**Comment by ASerbinski** [comment]
My question here; if an external signaling server is available, would it not make sense to make use of that to trigger pulling of new messages? Use long-polling as a fallback only, in case external signaling isn't available. Presumably, that could be done using the same connection that is used for the "{user} is typing..." messages.

**Comment by mahibi** [comment]
yes long polling should only be a fallback when external signaling server is available.
Handling of many signaling messages still needs to be implemented (https://github.com/nextcloud/talk-android/issues/2816)

**Comment by foegra** [comment]
I vote for this. Quite annoying, that new messages are not updated and chat has to be reopened.

**Comment by mahibi** [comment]
> I vote for this. Quite annoying, that new messages are not updated and chat has to be reopened.

which app version are you using?

**Comment by foegra** [comment]
Always the latest from Google Play

**Comment by mahibi** [comment]
We are going to make huge changes for the chat in the next months (offline support). So we might not invest time to fix the "old" code but hopefully come up with a much better version that will fix it by the way..

**Comment by mahibi** [comment]
fixed by implementing offline feature https://github.com/nextcloud/talk-android/pull/3952

**Comment by wallnoefertom-jpg** [comment]
Environment

Device: Google Pixel 8 Pro, Android 37
Talk Android app: v24.0.2 (gplay flavor)
Server: Nextcloud 34.0.1, Talk 24.0.3
Signaling Mode: External
Battery optimization: already set to Unrestricted (not the cause)
Notification permissions: granted, notification channels enabled

Symptom
Push notifications (Firebase) are delivered reliably — token generation and server/push-proxy registration timestamps are always fresh. However, after roughly half a day to a full day of normal use, the chat message list stops updating: the notification still shows up on the phone and on a paired watch, but opening the app/conversation shows stale, outdated messages. This has now happened 11 times.

What does NOT fix it

Force-stopping the app and reopening it: no effect, chat stays stale.
Toggling account sync off/on within the app: no effect.

What DOES fix it (temporarily)
Only a complete uninstall and reinstall of the Talk app resolves it. It then works fine again for anywhere from half a day to about a day before recurring.

Why this points away from a network/socket-level cause
Force-stopping the app kills the process entirely, which would clear any in-memory or socket-level state (e.g. a stuck/half-open WebSocket connection). Since force-stop + reopen did not fix the issue, and only a full uninstall (which wipes local app data/database) did, the root cause is likely something in the app's persisted local state (e.g. a stale sync cursor/timestamp or database entry) rather than a dangling network connection.

Cross-platform comparison
The same account/server used via the iOS Talk app remains stable and does not show this issue, using the same server-side signaling/push infrastructure. This further suggests the root cause is specific to the Android client's local state handling rather than the server, reverse proxy, or signaling server configuration.

Question
Is this the same underlying issue as #3146, or should this be tracked separately given the additional detail (uninstall-only fix, iOS unaffected)? Happy to provide further logs/system reports if useful.

**Comment by mahibi** [comment]
HI @wallnoefertom-jpg 
As the current issue is from 2024 and a lot of code changed, please open a new issue for this and also please provide the diagnosis report (Settings- advanced - diagnosis)
