### ISSUE TITLE
[Feature Req] App Shortcuts

### ISSUE THREAD

**Issue by SteveYoungs** [nextcloud/talk-android#342]
Accessing recent conversations via app shortcuts would be great.  'Create new conversation' would be another good candidate for a shortcut.

**Comment by te-online** [comment]
I'd like to try implementing this :-)

Any ideas on the icon to use for `New conversation`? 
Obviously recent contacts should have their avatar displaying instead of an icon, right?

**Comment by mario** [comment]
I guess the "+" from the FAB is a good option? :)

And yes, if they're one-to-one conversations that's indeed right.

**Comment by mario** [comment]
Hint: you should be able to use the database to get recent conversations, even if nothing in master is stable yet :)

**Comment by te-online** [comment]
Thanks for your input. Well, as you can see (https://github.com/te-online/talk-android/tree/feature/app-shortcuts) I have no idea what I'm doing... 😂 

Still need to figure out how to actually get the 3 latest conversations. Then I need to update the shortcuts accordingly. I guess they should always be up-to-date? And (probably *very* difficult): I need to figure out how put the white + on top of the blue background 😄 

But I'm getting there. If you have any input already, let me know, I'm happy to restructure or refactor if I'm doing stupid things...

**Comment by mario** [comment]
Hi @te-online - I appreciate you trying to help out. My internet access is VERY limited but I'll try to help as I can. While I didn't think of this in detail, the ideal approach might be:

- create a class that will be instantiated as singleton via Koin
- this class would have two observers:
  - current account observer (for purposes of New conversation shortcut)
  - 3 most recently updated (lastActivity) conversations (not ideal as we'd want ones we interacted with, but this will be good enough)

For first there's already LiveData in DAO implementation(s). For second you'd have to create one, but that shouldn't be hard.

Then you need to act on changes to both to update the shortcuts. Here's something for inspiration on that part (not usable per-se, but good as a source of learning):

https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/9fde5dbf4ffc58be20950c35a7a68f0336a3254e/TMessagesProj/src/main/java/org/telegram/messenger/MediaDataController.java

As for the + on blue background and conversation avatars: keep in mind they'll actually be assembled of two parts: the actual image + bottom right smaller image with an avatar of the relevant account.

Let me know if this helped or if I only complicated it further!

**Comment by mario** [comment]
Keep in mind most/(all?) apps actually only create&update shortcuts on app startup which is OK-ish, but not as good as above solution. I'd accept any of the two approaches for initial PR, if you feel like the above is too complex.

**Comment by te-online** [comment]
> My internet access is VERY limited but I'll try to help as I can. 

That's perfectly alright 😊 — thanks a lot!

I'm glad that I followed most of your advice intuitively already before you even posted it 🤓 

I added an observer but I still have to make it fire the change events – I'll look at the Telegram example for that.

I'll also take a look at the Singelton approach via Koin, maybe that's why my observer doesn't work, because I didn't inject the dependecies for the offlineStorage (or whatever the name is) correctly.

Regarding the icons, I'll look at that once everything else works, but I couldn't find an example in the app that would resemble the case that I need. Right now I can only have a blue background or an (invisible) plus icon on white. Somehow I need to combine them 🙈 But this is only for “New conversation“, obviously the recent conversations will have the avatar image, which I'll try to adapt from the chat list.

**Comment by mario** [comment]
Did you start observing livedata via observe method? Look at
newarch/feautures/conversations list view onCreateView method on how to do
that.

**Comment by te-online** [comment]
> Did you start observing livedata via observe method?

Yes, that's what I did 😊 But I did in in `MainActivity`. Now I moved instantiation of my service / class to `ConversationListView`, it works now :-) Although I'm not sure how I'd make this a singleton, since every `ConversationListView` will create another instance, right? 🤔 

I'll take a look at some polishing and then I might just open a PR to get some feedback on the approach. But no rush, it'll probably take me a while longer...

**Comment by te-online** [comment]
Hey @mario, maybe you can help me out on this one:

The only thing I'm missing is displaying the actual avatars for our shortcut conversations. But how would you approach that? I don't see a path right now.

I need to create an Icon that I can pass to `.setIcon()` on the shortcut builder.

But if I look at `ConversationItem.kt` there's a large chunk of logic going into fetching the correct (https://github.com/nextcloud/talk-android/blob/master/app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.kt#L249) avatar image, and whether to fetch an image at all, depending on the type of conversation. 

Of course I don't want to replicate all of this code within the shortcut service. But I don't see a way to re-use the code, because it attaches the image data directly to the view, without any chance for me to intercept or convert to an Icon for shortcut usage.

Any ideas? 🤔

**Comment by mario** [comment]
@te-online hey, glad you're still working on it! Did you push your latest code so I can take a look at it?

**Comment by te-online** [comment]
@mario Yeah, sure, thanks for getting back to me :-)
The current work-in-progress should be here: https://github.com/te-online/talk-android/tree/feature/app-shortcuts

**Comment by mario** [comment]
@te-online my latest commit adds some sugar to make this easier on you - please take a look and let me know if you have any questions.

https://github.com/nextcloud/talk-android/commit/1f6d3a1a639e93a1253e00065bd572f79e941c8d

For the actual one-to-one icon I assume you'll want either the imperative Coil.get() or use a target and then set the drawable.

If you need any clarifications, I'm here!

**Comment by mario** [comment]
@te-online if you can rebase on latest master and give me access to your repo maybe I can help you more directly, if you wish? :)

In the future we could definitely grant you access to this repo so you could create branches here if you plan to keep doing awesome stuff!

**Comment by te-online** [comment]
Cool! Not sure if that rebase worked, but you should now be a collaborator on the repo, otherwise it should be public already, right? I really would like to contribute more, but I can't always fit it in. However, I thought this issue might be a good start, because it had the `good first issue` label. Developing for Android is not something that I find “easy” right now, but I'm hoping to change that in the future. But until then, I will try to contribute, but it might be a slow and long-winding path... 😉

**Comment by mario** [comment]
Changing milestone to earlier thanks to the awesome @te-online. Maybe still a bit work left, but there's a PR now for you to look at @te-online :))

Thank you, you're awesome!

**Comment by mario** [comment]
Closing thanks to awesome @te-online !!!
