### ISSUE TITLE
No indication of outgoing call *no ringing*

### ISSUE THREAD

**Issue by bonafideb** [nextcloud/talk-android#364]
There's no indication of an outgoing call other than the "connecting..." disappearing. It is silent with no ringing so it is hard to differentiate whether or not the call is still 'ringing' or has been established by the other end.

**Comment by mario** [comment]
I am sorry that the experience of using the app has been less than optimal. For your desired functionality we would need certain changes in the server part of the Talk/Spreed.

Since this functionality has already been requested in #254 for the Talk Android app, I'll close this ticket right here, but will be sure to update you and others there in case something changes in the future.

Thank you for using the app and caring enough to file an issue!
