### ISSUE TITLE
E2E encrypted push notifications

### ISSUE THREAD

**Issue by oliob** [nextcloud/talk-android#393]
Hi,

are the push notification payloads (e.g. the message bodies) actually end-to-end encrypted?

By default, FCM uses https between the NC server and the Google server and ssl over tcp between the FCM Google servers and the Android device. However the payload of the push message is readable for the Google servers.
There is a description on how to enable E2E for FCM here:
https://android-developers.googleblog.com/2018/06/project-capillary-end-to-end-encryption.html?m=1
They provide a library for this.

I briefly looked at Android Talk code but I haven't seen any E2E for the push notifications or I just missed it.

If push notifications are not E2E encrypted this is actually a huge data privacy issue IMO.

Cheers,
O

**Comment by mario** [comment]
Hello @oliob. I appreciate your concern for the security when it comes to push notification payloads - this is indeed a huge topic. As you probably know, since you're following Nextcloud, we invest quite a lot of time and energy into making sure that everything is properly secured.

While we don't use Project Capillary to achieve payload end-to-end encryption, we do achieve end-to-end encryption using other means, therefore the content of the push notification cannot be read by third-parties like Google servers. 

I can point you to the following file which contains fragments of how we do the whole decryption process - which is - specific to your device since only YOUR device holds the required private key.

I hope this clarifies and removes all your doubts about the security when it comes to notifications payload. If not, let me know and I will be more than happy to explain this further.

**Comment by oliob** [comment]
Thank you very much for your clarification @mario !

> I can point you to the following file which contains fragments of how we do the whole decryption process - which is - specific to your device since only YOUR device holds the required private key.

I guess your link to the file got lost ;-)

**Comment by mario** [comment]
Sorry about that @oliob - https://github.com/nextcloud/talk-android/blob/master/app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.java :)
