### ISSUE TITLE
cant call with app

### ISSUE THREAD

**Issue by jookk** [nextcloud/talk-android#395]
Galaxy j3 2017 android 8
Started call - only loading spinner. Probably only with audio call. Video sometimes working sometimes not.
Local net.
Switched off syn-flood and ddos protection on router. But ...

**Comment by gradinaruvasile** [comment]
Can confirm. App version 3.1.2 has calling issues (can pick up direct calls but cannot join any kind of call, direct or group).
Downgraded to 3.1.1 and outgoing calls are working again.

**Comment by jookk** [comment]
Nc 15.app 3.1.2 -
Anorher issue:
Start call -> on receiving phone only short ring but in moment ring stop, (as caller canceled call) but caller is still waiting to hang up.

**Comment by mario** [comment]
Please let me know if this works in 3.1.3! :)

Thanks!

**Comment by gradinaruvasile** [comment]
Yes, it seems to be working correctly with 3.1.3

On Dec 28, 2018 15:26, "oliob" <notifications@github.com> wrote:

Can confirm the bug described by OP. Seems working now with 3.1.3.
Thanks Mario!!!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/nextcloud/talk-android/issues/395#issuecomment-450359092>,
or mute the thread
