### ISSUE TITLE
Add GIF (Giphy) keyboard

### ISSUE THREAD

**Issue by mario** [nextcloud/talk-android#411]

**Comment by jookk** [comment]
Mario, can you add google gif keyboard too? When I want to add some gif from g keyboard, it only flash info, that talk app do not support gif pasting to this (text box) area.

**Comment by mario** [comment]
I am not sure what a Google GIF keyboard is. Can you ssend me a link to the app?

**Comment by q-wertz** [comment]
Is there any plan to "fix" the `Nextcloud Talk unterstützt das Einfügen von Bildern hier nicht` (freely translated `Nextcloud Talk does not support adding of images here` behavior or is it intended?

**Comment by mahibi** [comment]
what is a giphy keyboard?

@q-wertz what are you trying to do? when does this message appear?

**Comment by q-wertz** [comment]
It happens when I enter the GIF menu (I think thats the same @jookk mentioned)
![Screenshot_20210427-231351](https://user-images.githubusercontent.com/20948931/116313858-dc244280-a79d-11eb-827b-b8d1f9e1eb50.png)

And then try to add a GIF

![Screenshot_20210427-231140](https://user-images.githubusercontent.com/20948931/116313871-e0506000-a79d-11eb-9836-52f88c43d666.png)

BTW: it is the same when trying to add these "strange" special smileys of the keyboard (button on left of GIF in first picture)
But shouldn't this behave the same way as adding something from local storage?
