### ISSUE TITLE
Why Nextcloud Talk App is not saving Conversations to local (SQLite) database?

### ISSUE THREAD

**Issue by developerfromjokela** [nextcloud/talk-android#449]
# Hello!

I likes the app, but there is one question.

Why the app is not saving Conversations and messages to database, because all other char apps are doing this, like XMPP clients.

If it's because security, maybe data can be encrypted?
 
If I have enough time, I can Implement it.

Regards,
@developerfromjokela

**Comment by mario** [comment]
Because we do not have offline support just yet - there is an open issue for that :) Once we do, we'll only use the messages from the DB and update via network calls. Requery (the DB abstraction layer) we use does allow constant fetching, but we'd maybe move to Room if we get the time.

So I'll close this ticket since there already is one, but you're more than welcome to discuss your ideas and then implement it - everybody would be very happy about it! :)
