### ISSUE TITLE
Notification sound

### ISSUE THREAD

**Issue by Scoub29** [nextcloud/talk-android#64]
Hello,
Is it possible to choose another notification sound for incoming call than the smartphone default one ?
A long ringtone would be better than a short notification ;)
Best regards

**Comment by mario** [comment]
Not yet. But the plan is to support this eventually :)

**Comment by BloodyIron** [comment]
Yeah, really need to get at least a basic sound notification here. If someone wants to call me, I'm going to easily miss it by not having any sound. Can we get this with a higher priority please?

**Comment by mario** [comment]
@BloodyIron you should have the default ringtone right now. Don't you get it ringing when you get a phone call?

**Comment by BloodyIron** [comment]
@mario I just tested with a demo instance of NC13, then added the Talk app to the system. Then set my Android phone up with the demo instance, and that's the only account configure in the Android Talk app on my phone.

I then take Firefox, log into the demo instance with User1. Start call with User2 (the phone is using this account).

On the phone, for User2, I see the graphical notification come up, but ZERO sound plays. Nothing is muted, I know this, because I get sounds when I type and I'm getting other alerts too.

So yeah, this, as well as my internal testing, shows no audible alerts for incoming Android Talk "calls".

**Comment by mario** [comment]
@BloodyIron thanks for testing. This is then a bug as it really should work and something must have gone wrong along the way.

**Comment by BloodyIron** [comment]
@mario it would be nice also if we could get a setting to change the notification sound (when it works).

Additionally, since I have no idea what the actual default sound is, I think it would be a good idea if NC-Talk had a unique (compared to other apps) sound used for notifications. This could already be the case, and if it is, disregard this part. But a default behaviour of having it blend in to notification sounds, makes it easy to "ignore".

Either way, yeah, it's not working for me just yet :P

**Comment by mario** [comment]
@BloodyIron, in theory, you can do that by changing the default ringtone sound in your Android settings. But like we concluded, for some reason, it does not work. I'll investigate.

**Comment by BloodyIron** [comment]
Having the NC-Talk sound tied to the system alert noise defeats the point of having a separate noise for it. So, if you could take a gander at that while you're poking around, that'd be swell! :)

**Comment by BloodyIron** [comment]
Why was this closed suddenly?

**Comment by mario** [comment]
@BloodyIron because I'm a very mean person and I will not do it :P

Joking aside, it's been implemented and will be available in 2.1. :)

**Comment by BloodyIron** [comment]
@mario lol! Thanks! :D

**Comment by Scoub29** [comment]
Thanks a lot !! ;)
