### ISSUE TITLE
Ease of use

### ISSUE THREAD

**Issue by danielschramm** [nextcloud/talk-android#759]
Hello,

I intended to use this app for a special user group.
Children in elementary school with small closed user group who should not use WhatsApp or similar.

The functionality of the app is really great
But the usability is really bad from this point of view.
 
Use Case 1 Video Call ringing - second Phone app not open:
- One person starts a  video chat
- the other Phone shows only an info popup which goes away on click.
- It's important to directly accept the  call inside this popup

Use case 2 Video Call ringing - second phone app open:
- Even with app open there is no clear indication that someone is calling
- only inside the chat is a text message showing the incoming call. This is not clear for persons just leaning reading
- if the popup was quit it's hardly possible to find the person who was calling

Use Case 3: Accepting Call
- When we were finally able to find out who was calling it's not clear if the other side issued an audio or video call.
- I think this is intended but not a good usability for children or handicapped.
- there should be a config option to replace the 3 button option with just accept and decline.

Nice to have:
- I did not find it, might already be implemented:  have the possibility to replace the Capital Letter indicating the user with a picture.

Thanks 

Daniel Schramm

**Comment by mario** [comment]
Hi. 

Use case 1: The notification popup is intentional in case of group or public calls as we don't want a full screen that keeps ringing shown for those.
Use case 3: you have to file an issue on the server for this - currently we indeed don't know if it's a voice or video call. https://github.com/nextcloud/spreed

Nice to have: You have to upload an avatar as a user in your Nextcloud and then you'll get a picture.
