### ISSUE TITLE
beta3: chat is not loading

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#803]
If you enter a chat, the messages aren't loaded. You have to leave the chat enter it again three times, than it shows the messages.

**Comment by mario** [comment]
What?! o.O Wow. Thanks for reporting :-/ 

I'll investigate.

**Comment by guzzisti** [comment]
Similar behaviour here:
i've entered the settings and changed the notification sounds. After that i wanted to enter a chat, but the loading circle never disappeared and the heading said "settings" instead showing the name of the chat.
After reentering the app, the chat could be loaded successfully.

**Comment by simonspa** [comment]
Might also be related to entering a conversation through a notification. At least that's when I observed this behavior the most.

**Comment by guzzisti** [comment]
This happens again with 9.0.0beta5. After starting the app i immediately entered the settings and than going back to the chat list. After that a chat will not load anymore.
The rotating circle appears and the header shows "Settings" instead of the chat name. The call/videocall icons are there, but the chat history won't load and the input field is missing.

After a complete app restart it might work again in some cases, but going back and forth through apps this happens again after a short period of time.
