### ISSUE TITLE
Vibration issues on Android 9 

### ISSUE THREAD

**Issue by gradinaruvasile** [nextcloud/talk-android#855]
The vibration control of the app is atrocious.
If i call a phone with the app, it will keep vibrating even after the call is established for minutes.
If the phone does not pick it up it will just go on vibrating for minutes, extremely annoying.
If the user has more than 1 mobile devices, both will ring and one picks up the other keeps ringing for presumably the duration of the call.

The app is pretty much useless for calling this way.
I tested it on 3 phones, one Lenovo with Lineage OS, one Nokia and One Xiaomi A1 both with Android 9. All exhibit the same behavior.

Server is 18.0.4
Spreed app is 8.0.9
Android Talk app is 8.0.9

Edit:

The issue here is that the vibration keeps on even after user action is taken like accept or reject the call, until i kill the app or it has at least 1 minute-like timeout after user action (and the very long timeout, if it even exists, for unanswered calls). It is very unpleasant user experience to have the phone vibrating with no idea where it is coming from.

**Comment by dhsc19** [comment]
I have the same problem.  And I can reproduce it consistently.

1.  The receiving phone is in vibrate mode.
2.  The receiving phone is screen locked (meaning it is in the state where you would need to enter your PIN, or password, or fingerprint to unlock)
3.  Initiate call to the receiving phone.
4.  The receiving phone let's you answer the call over the locked screen (as it should}.
5.  When you answer, the vibrate will continue to keep going unless you turn the screen off and on (i.e. press the power button twice).

This does not happen when the screen is unlocked because it seems that on an unlocked screen a notification pops up first and pressing the notification stops the vibrate before the answer/hang up screen comes on.  Interestingly, pulling the notification drawer down stops the vibration too.  But, doing that doesn't take you to the answer/hang up screen and you may not realize that the call is actually still waiting to be answered.

When the phone is NOT in silent mode and screen is unlocked, pressing the notification takes you to the answer/hang up screen and the ringing doesn't stop until you actually answer the call.  If you pull down the notification drawer instead, the ringing is stopped.  But since you are not taken to the answer/hangup screen, you may not realize the call so needs to be answered.

**Comment by w1zk1d** [comment]
Any solution to this?

**Comment by nickvergessen** [comment]
Hello there,

we are currently cleaning up old/stray github issues. Can you please retry with the current version and report back if the problem still persists for you?

cheers
