### ISSUE TITLE
Make unsent messages persist

### ISSUE THREAD

**Issue by 05nelsonm** [nextcloud/talk-android#880]
Current behavior:
Type a message to another user, exit app, come back, message is not there.

If the application goes to the background and is killed by the OS, unsent messages are lost.

Using onSavedInstanceState to recover from process death would be a great nicety to have.

**Comment by ctilluma** [comment]
I think there are two ways we can address this issue, depending on whether online or offline. Online will be easier, as we have to write into the savedinstance, but this is something that needs to be done for #830 so that we can also remember where in the list of messages we scrolled to. 

The second will be maintaining a state of the sync on the app so it knows when it reconnects which messages it needs to send and check for newer.

**Comment by nickvergessen** [comment]
#1259  might help already

**Comment by mahibi** [comment]
resolved since https://github.com/nextcloud/talk-android/pull/3224
