### ISSUE TITLE
Enhance buttons during call

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/talk-android#910]
- switch camera transparent background (in own video)
- all buttons on bottom black half transparent background instead of blue
- screen share on bottom
- chat: top left, but black half transparent
- all buttons in one row:
- mute, hide camera, three dot menu (with screen share, toggle to speaker), end call

For reference but this is not the spec: https://user-images.githubusercontent.com/1589737/75161351-ed963880-571b-11ea-8bf3-1f2812768b15.png

**Comment by jancborchardt** [comment]
Nice @tobiasKaminsky! Just chatted with @Ivansss for coordination also on iOS, some points from there:
- The way the buttons look like on iOS is quite nice, let’s go for that on Android too:
   - background is `#999999` grey at 75% opacity
   - icon color should be white
- When in the chat view, the "back to call" icon should be floating on the top right and have feedback of the call being active. This is nicely done on iOS as well with the pulsing feedback. @Ivansss for reference.
- iOS Talk should move the "go back to messages" button to the top left, and the own video to the top right. Also cause the front-facing camera on iPhones tends to be on the right rather than left.
- On iOS as well as Android we should ideally have some sort of animation between the 2 views. "Physically" the chat view is left of the call view, so the chat view should slide in from the left, and going back to the call view should slide in from the right.

**Comment by tobiasKaminsky** [comment]
>     * When in the chat view, the "back to call" icon should be floating on the top right and have feedback of the call being active. This is nicely done on iOS as well with the pulsing feedback. @Ivansss for reference.

If there is no call active then the icon is not shown?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @nickvergessen I think checking the latest v12 Alphas this is done, no?

**Comment by mahibi** [comment]
yes this is done. missing TODOs are in the notes from the design calls
