### ISSUE TITLE
Videocall - screen goes completely black

### ISSUE THREAD

**Issue by ringogalga** [nextcloud/talk-android#920]
Hi,
When I'm on a video call the screen goes completely black when you hold the phone to your ear, totally ok. But this also happens very often when I am in a video chat and not only to me but also to friends.
Tested with:
Oneplus 7
Xiaomi Mi Red 9
Latest Android version

**Comment by tobiasKaminsky** [comment]
As far as I know this feature uses proximity sensor.
Do you have some kind of screen protection sheet? Does this happens also on a regular call?

Or is this maybe your screen timeout?

**Comment by ringogalga** [comment]
I have no screen protection
I don't check it if it happens on regular call, sry can it test the days only at the next call

**Comment by ringogalga** [comment]
> 
> 

> Does this happens also on a regular call?
> 
Now I have checked it with regular call. The issue is only via video call

**Comment by shafer** [comment]
I've experienced this problem on my Nokia 7.1 phone.

Also experienced by other users of the android app that are part of my Nextcloud install.

I have no screen protector. It seems like the proximity sensor isn't deactivated for video calls. Possibly related the audio doesn't seem like it's being routed through the speaker like it should for a video call. It's very quiet like for a voice call with the handset held next to your head.

**Comment by Chluz** [comment]
Reopening as this is still an issue on v12.2.1.
I have it happening on the  Poco F3, which happens to have an ultrasonic proximity sensor. When the screen turns off, it's either during an audio speaker call, or during a video call. On my phone, this can happen due to mild proximity, or the screen being angled whilst in call. I then need to manually approach my hand to the sensor and take it away to retrigger the deactivation of proximity mode. Its particularly annoying. For me the sounds is coming through correctly.
