### ISSUE TITLE
Drops call when minimizing app

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/talk-android#938]
When joining the meeting the call is working with no issues. If you minimize the app while being on the call and reopen it you do get the video on the callers back you have to leave and rejoin the meeting for it to work. From what i can recall it worked before 8.1.0 version

**Comment by tobiasKaminsky** [comment]
Can the other person still hear you? And do they see that you are still in call?

**Comment by axheli** [comment]
@tobiasKaminsky Nope can hear or see each other. after i leave the meeting on the talk app and rejoin then it works but if i minimize the app and maximized it back to the same problem.

**Comment by tobiasKaminsky** [comment]
> And do they see that you are still in call?

This is the important part, as then I know if the app is still connected to the other user.

**Comment by axheli** [comment]
> > And do they see that you are still in call?
> 
> This is the important part, as then I know if the app is still connected to the other user.

Nope they dont see me! It's like the person leaves the call.

**Comment by axheli** [comment]
@tobiasKaminsky  just wanted to let you know that I downgraded to 8.0.10 and i don't see this issues so definably something wrong in V8.1.0

**Comment by axheli** [comment]
@tobiasKaminsky  same issue on the version before but it doesn't happen right away in 8.1.0 happens right away

**Comment by axheli** [comment]
@tobiasKaminsky another comment i noticed if your phones display goes black and back to wake up the video is disable you have to click on the video icon and back on to get the camera to work

**Comment by some-git-user** [comment]
Having the same issue with three Android devices (Android version 5, 9 and 10) too.
Also sometimes the connection from the Android client timed out, leaving the client with frozen screen and no audio.
Example:

Client 1 temporary loses connection to nextcloud server during videocall.
Client 2 and 3 seeing last transmitted freeze frame from client 1.
Client 1 seeing last transmitted freeze frame from client 2 and 3.

At this point client 1 is unable to auto reconnect to the running videocall session. No audio or video recovery.
Only leaving the call, or forcing the app to close (not responding while hang up) and recall "solves" the problem.

We are using our Nextcloud infrastructure as babyphone/babymonitor and its unpleasant to not knowing/seeing if the connection broke down. This problem is leaving us with last freeze frame from our toddler and we thinking everything is fine :(

**Comment by andyxheli** [comment]
Still an issue

**Comment by andyxheli** [comment]
@tobiasKaminsky hope you're doing well do you have any eta on this?

**Comment by tobiasKaminsky** [comment]
Why are you pinging me directly and ask for eta? This is not how we work here on github?

**Comment by andyxheli** [comment]
You originally responded to the issue so was sure it would handle it or not my bad.

**Comment by andyxheli** [comment]
> Why are you pinging me directly and ask for eta? This is not how we work here on github?

I wasn't sure since you asked a few questions at the beginning i though maybe you would be working on it thats why. But now i know and wont bug you.

**Comment by EthanHindmarsh** [comment]
I am having this issue as well, I have to reconnect any time I minimize the Android app. My friend on iOS does not seem to have the same problem

**Comment by mahibi** [comment]
this is solved with https://github.com/nextcloud/talk-android/pull/1655
However there still needs to be a solution when picture in picture is not available, see https://github.com/nextcloud/talk-android/issues/1688
